language: python
python:
  - 3.4
  - 3.5
  - 3.5-dev
  - nightly
install:
  - pip install .
  - pip install coveralls
script: 
  - coverage run --source=dhcpkit setup.py test
after_success:
  - coveralls
